[[mgr.prepend_keymap]]
on  = "<D-y>"
run = ["plugin system-clipboard"]

[[mgr.prepend_keymap]]
on  = "<C-p>"
run = 'shell -- qlmanage -p "$@"'

[[mgr.prepend_keymap]]
desc = "Cycle through previewers"
on   = "p"
run  = "plugin mux --args=next"

[[mgr.prepend_keymap]]
desc = "Toggle media metadata"
on   = "<F9>"
run  = "plugin mediainfo --args=toggle-metadata"

[[manager.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- ripdrag -x -i "$@"'