# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
linemode       = "size_and_mtime"
ratio          = [1, 2, 3]
show_hidden    = true
show_symlink   = true
sort_by        = "alphabetical"
sort_dir_first = true
sort_reverse   = false
sort_sensitive = false

[preview]
cache_dir       = ""
image_delay     = 0
max_height      = 5000
max_width       = 5000
tab_size        = 4
ueberzug_offset = [0, 0, 0, 0]
ueberzug_scale  = 1
wrap            = "yes"

[opener]
edit = [
    { run = 'code "%*"', orphan = true, for = "windows" },
    { run = 'nvim "$@"', block = true, for = "unix" },
]
extract = [
    { run = 'unar "$1"', desc = "Extract here", for = "unix" },
    { run = 'unar "%1"', desc = "Extract here", for = "windows" },
]
open = [
    { run = 'open "$@"', desc = "Open", for = "macos" },
    { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
    { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]
play = [
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
    { run = 'mpv "%1"', orphan = true, for = "windows" },
    { run = 'mpv --vo=libmpv --geometry=50% --no-border --focus-on=open --mute=yes "$@"', orphan = true, for = "unix" },
]
reveal = [
    { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
    { run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
    { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
]
rootbrowse = [{ run = 'rootbrowse "$1"', orphan = true, for = "unix" }]
zathura = [{ run = 'zathura "$1"', orphan = true, for = "unix" }]

[open]
rules = [
    { mime = "audio/*", use = [
        "play",
        "reveal",
    ] },
    { mime = "image/*", use = [
        "open",
        "reveal",
    ] },
    { mime = "inode/x-empty", use = [
        "edit",
        "reveal",
    ] },
    { mime = "text/*", use = [
        "edit",
        "reveal",
    ] },
    { mime = "video/*", use = [
        "play",
        "reveal",
    ] },
    { name = "*/", use = [
        "edit",
        "open",
        "reveal",
    ] },

    { mime = "*/javascript", use = [
        "edit",
        "reveal",
    ] },
    { mime = "application/json", use = [
        "edit",
        "reveal",
    ] },
    { mime = "application/pdf", use = [
        "reveal",
        "zathura",
    ] },
    { name = "*.root", use = [
        "rootbrowse",
    ] },

    { mime = "application/gzip", use = [
        "extract",
        "reveal",
    ] },
    { mime = "application/x-7z-compressed", use = [
        "extract",
        "reveal",
    ] },
    { mime = "application/x-bzip", use = [
        "extract",
        "reveal",
    ] },
    { mime = "application/x-bzip2", use = [
        "extract",
        "reveal",
    ] },
    { mime = "application/x-rar", use = [
        "extract",
        "reveal",
    ] },
    { mime = "application/x-tar", use = [
        "extract",
        "reveal",
    ] },
    { mime = "application/xz", use = [
        "extract",
        "reveal",
    ] },
    { name = "application/zip", use = [
        "extract",
        "reveal",
    ] },

    { mime = "*", use = [
        "open",
        "reveal",
    ] },
]

[tasks]
bizarre_retry    = 5
image_alloc      = 536870912 # 512MB
image_bound      = [0, 0]
macro_workers    = 25
micro_workers    = 10
suppress_preload = false

[plugin]
prepend_preloaders = [
    { mime = "image/*", run = "mediainfo" },
    { mime = "video/*", run = "mediainfo" },
]
prepend_previewers = [
    # Video and image with metadata
    { mime = "image/*", run = "mediainfo" },
    { mime = "video/*", run = "mediainfo" },

    # Audio metadata and covers
    { mime = "audio/*", run = "exifaudio" },

    # Markdown and CSV with piper
    { mime = "text/csv", run = "mux miller code" },
    { name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },

    # Archive previewer
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-bzip", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/xz", run = "ouch" },
    { name = "application/*zip", run = "ouch" },
]
previewers = [
    { name = "*/", run = "folder", sync = true },
    # Code
    { mime = "*/javascript", run = "code" },
    { mime = "*/x-wine-extension-ini", run = "code" },
    { mime = "*/xml", run = "code" },
    { mime = "text/*", run = "code" },
    # JSON
    { mime = "application/json", run = "json" },
    # Image
    { mime = "image/*", run = "image" },
    { mime = "image/vnd.djvu", run = "noop" },
    # Video
    { mime = "video/*", run = "video" },
    # PDF
    { mime = "application/pdf", run = "pdf" },
    # Archive
    { mime = "application/gzip", run = "archive" },
    { mime = "application/x-7z-compressed", run = "archive" },
    { mime = "application/x-bzip", run = "archive" },
    { mime = "application/x-bzip2", run = "archive" },
    { mime = "application/x-rar", run = "archive" },
    { mime = "application/x-tar", run = "archive" },
    { mime = "application/xz", run = "archive" },
    { mime = "application/zip", run = "archive" },
]

[input]
# cd
cd_offset = [0, 2, 3, 50]
cd_origin = "top-center"
cd_title  = "Change directory:"

# create
create_offset = [0, 2, 3, 50]
create_origin = "top-center"
create_title  = ["Create (dir):", "Create:"]

# rename
rename_offset = [0, 1, 3, 50]
rename_origin = "hovered"
rename_title  = "Rename:"

# trash
trash_offset = [0, 2, 3, 50]
trash_origin = "top-center"
trash_title  = "Move {n} selected file{s} to trash? (y/N)"

# delete
delete_offset = [0, 2, 3, 50]
delete_origin = "top-center"
delete_title  = "Delete {n} selected file{s} permanently? (y/N)"

# filter
filter_offset = [0, 2, 3, 50]
filter_origin = "top-center"
filter_title  = "Filter:"

# find
find_offset = [0, 2, 3, 50]
find_origin = "top-center"
find_title  = ["Find next:", "Find previous:"]

# search
search_offset = [0, 2, 3, 50]
search_origin = "top-center"
search_title  = "Search:"

# shell
shell_offset = [0, 2, 3, 50]
shell_origin = "top-center"
shell_title  = ["Shell (block):", "Shell:"]

# overwrite
overwrite_offset = [0, 2, 3, 50]
overwrite_origin = "top-center"
overwrite_title  = "Overwrite an existing file? (y/N)"

# quit
quit_offset = [0, 2, 3, 50]
quit_origin = "top-center"
quit_title  = "{n} task{s} running, sure to quit? (y/N)"

[select]
open_offset = [0, 1, 50, 7]
open_origin = "hovered"
open_title  = "Open with:"

[log]
enabled = false


# git
[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
